### ISSUE TITLE
 licence?

### ISSUE THREAD

**Issue by aguilaair** [TheAlphaApp/flutter-task-planner-app#1]
Hello, I'd like to base my project in your app, what licence should I ahere to?

Kind regards,
Eduardo.

**Comment by TheAlphaApp** [comment]
Sorry, I can't understand your problem. But first let me explain myself. I am a civil engineer. I started to do programming just for fun (as a hobby). I've no plans ahead in programming for now. I don't know about 'license' ( and also I don't know about many things in programming field). Should I make a license for this project to be used by others??  If you want to use this project, you can use this for free. Thank you.

**Comment by aguilaair** [comment]
Thank you for the information! What I meant by my reuqest was excatly this. So, in other words how can I use the project? Should I attribute it, am I able to use it under a different liscence/agreement. You can take a look at MIT, GLP v3 or Mozilla. 

Another common liscence is the Creative Commons: https://creativecommons.org/share-your-work/
It is quite popular as you can just choose how you want your work to be used and it will generate the best liscence for you.

https://chooser-beta.creativecommons.org/
https://creativecommons.org/choose


Thanks in advance!

**Comment by TheAlphaApp** [comment]
Thanks.
I added a license.

Regards,
Sourav
