### ISSUE TITLE
Looking to adding functioning backend implementation

### ISSUE THREAD

**Issue by prem5102** [TheAlphaApp/flutter-task-planner-app#8]
Hey, I looking to make this app a functioning one with state management & backend implementation of graphql server using node js. i willing to make backend for this.

**Comment by TheAlphaApp** [comment]
> Hey, I looking to make this app a functioning one with state management & backend implementation of graphql server using node js. i willing to make backend for this.

Hi, 
Thanks for your interest in this project. I've designed only the UI part. I had no plans further.  These days,  I'm a little tied up with my work. So, I don't have much time to work on the project. If you can work on this repo. You're welcome. It will be appreciated. Thanks.

**Comment by prem5102** [comment]
Thanks reply
